In [3]:
import pandas as pd
import numpy as np
from numpy.random import default_rng

In [4]:
my_list = [x * 10 for x in range(1, 11)]
my_list = np.array(my_list)
my_list.ndim
my_list.size
my_list.shape
my_list.dtype

dtype('int32')

np.ones((rows, cols), dtype) - all ones
np.zeros((ros, cols), dtype) - all zeros
np.arange(start, stop, step) - similar to range in base python
np.linspace(start, stop, n) - array of floats with start and stop with n elements consistent step size inclusive
np.array.reshape(rows, cols) - changes an array into the specified dimensions if compatible
np.identity(10) - identity matrix with 10 rows
np.array.T - Transpose the dimensions

np.random.seed(289)

np.random.rand() - single random number between 0 and 1
np.random.rand(5) - array of 5 random numbers
np.random.rand(3, 2) - 3x2 array of random numbers
np.random.randint(low = 1, high = 10) - random integer between 1 and 10
np.random.randint(low = 1, high = 10, size = 5) - array of 5 random integers
np.random.normal(mu, sigma, n)

In [11]:
rng = np.random.default_rng(289)  # if only import is import numpy as np

rng = default_rng(289)
random_array = rng.random(10)  # uniform random distribution
random_normal = rng.normal(mean=0, stddev=1, size=10)  # uniform random distribution
random_integers = rng.integers(0, 10, 100)  # uniform random distribution of integers

In [20]:
test_array = (np.arange(10).reshape(5, 2) + 1) * 10
test_array = np.linspace(10, 100, 10, dtype=int).reshape(5, 2)

In [21]:
test_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [23]:
test_array = np.random.rand(9).reshape(3, 3)

In [17]:
test_array

array([[0.41915156, 0.64476806, 0.33686719],
       [0.2181498 , 0.11207166, 0.83996187],
       [0.33577696, 0.28560386, 0.49931117]])

array[index]
array[start:stop:step_size]

single dimensional array
array[:5], first five elements
array[5::2] start with element index 5 then go everyother

2 dimensional array
array[start:stop:step_size, start:stop:step_size] [row, column]

In [32]:
# first two rows
test_array[:2, :]

array([[0.99485323, 0.67497056, 0.67696224],
       [0.23210741, 0.09953129, 0.73562335]])

In [31]:
# firt column
test_array[:, :1]

array([[0.99485323],
       [0.23210741],
       [0.61846933]])

In [27]:
test_array[2, 1]

0.43406535354743914

In [28]:
test_array

array([[0.99485323, 0.67497056, 0.67696224],
       [0.23210741, 0.09953129, 0.73562335],
       [0.61846933, 0.43406535, 0.17538661]])

In [35]:
rng = np.random.default_rng(289)

inventory = (rng.integers(0, 100, 10) / 2).round(2)

In [42]:
prices = (rng.random(6) * 10).round(2)
total_prices = (prices + 5) * (1 - rng.random(6))

In [43]:
total_prices

array([0.38050191, 3.61340534, 1.34425718, 6.04510713, 3.60692499,
       4.31451214])

In [45]:
prices + 5

array([11.09, 10.24, 10.96,  8.76, 10.28, 13.87])

In [48]:
(prices + 5) * (1 - rng.random(6)).round(2)

array([10.3137,  4.8128,  3.9456,  0.1752, 10.1772,  2.4966])

can combine logical tests in nparrays

sales_array[(sales_array == 616) | (sales_array < 100)]
sales_array[(sales_array > 100) & (sales_array < 500)]

mask = (sales_array > 100) & (sales_array < 500)

product_array[sales_array > 0] 

sales_array[sales_array == 0] = 5

In [49]:
even_odd = np.array(["even", "odd"] * 10)

In [51]:
even_odd[even_odd != "odd"]

array(['even', 'even', 'even', 'even', 'even', 'even', 'even', 'even',
       'even', 'even'], dtype='<U4')

where() funciton performs a logical test and returns a given value if the test is True. or another if the test is False

np.where(
    logical test,
    value if True,
    value if False
)

In [71]:
prices = rng.integers(15, 50, 6)
products = np.array(
    ["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"]
)
shipping_cost = np.array([5, 5, 0, 0, 5, 0])

In [77]:
prices.where(prices > 20, "high", "low")

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [73]:
expensive_product = products[(prices > 25) | (products == "cola")]

expensive_product

array(['salad', 'bread', 'rare tomato', 'cola'], dtype='<U17')

In [78]:
shipping_cost = np.where(prices > 20, 0, 5)

In [79]:
shipping_cost

array([0, 0, 5, 0, 5, 0])

array aggregation methods

calculate metrics like sum, mean, max...

nparray.sum() - sum of all values in array
nparray.mean() - mean of array
nparray.max() - max in array
nparray.min() - min in array

nparray.sum(axis = 0) sum across the rows (column 1 sum, column 2 sum, column 3 sum...) sum of all the rows in each column
nparray.sum(axis = 1) sum accross the columns(row 1 sum, row 2 sum, ...) sum of all the columns in each row

array functions

np.median(array)

In [81]:
sales_array = rng.integers(10, 20, 20).reshape(2, 10)

In [84]:
sales_array

array([[16, 10, 11, 14, 19, 18, 13, 11, 11, 17],
       [18, 15, 10, 13, 19, 12, 15, 12, 10, 10]], dtype=int64)

In [83]:
np.median(sales_array)

13.0

In [85]:
# percentile in data, this value should be greater than 90% of the data
np.percentile(sales_array, 90)

18.1

In [86]:
np.unique(sales_array)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64)

In [87]:
np.sqrt(sales_array)

array([[4.        , 3.16227766, 3.31662479, 3.74165739, 4.35889894,
        4.24264069, 3.60555128, 3.31662479, 3.31662479, 4.12310563],
       [4.24264069, 3.87298335, 3.16227766, 3.60555128, 4.35889894,
        3.46410162, 3.87298335, 3.46410162, 3.16227766, 3.16227766]])

In [88]:
sales_array.sort()

In [89]:
sales_array

array([[10, 11, 11, 11, 13, 14, 16, 17, 18, 19],
       [10, 10, 10, 12, 12, 13, 15, 15, 18, 19]], dtype=int64)

sales_array.sort(axis = 0) looks at columns

sales_array.sort(axis = 1) looks at rows

In [90]:
sales_array.sort(axis=0)
sales_array

array([[10, 10, 10, 11, 12, 13, 15, 15, 18, 19],
       [10, 11, 11, 12, 13, 14, 16, 17, 18, 19]], dtype=int64)

In [91]:
sales_array.sort(axis=1)
sales_array

array([[10, 10, 10, 11, 12, 13, 15, 15, 18, 19],
       [10, 11, 11, 12, 13, 14, 16, 17, 18, 19]], dtype=int64)

In [93]:
sales_array[0::-1]

array([[10, 10, 10, 11, 12, 13, 15, 15, 18, 19]], dtype=int64)

In [97]:
test = rng.integers(10, 20, 20)

In [98]:
test

array([11, 14, 14, 10, 13, 15, 17, 14, 18, 15, 17, 16, 16, 16, 17, 15, 10,
       15, 16, 15], dtype=int64)

In [99]:
test.sort()

In [100]:
test

array([10, 10, 11, 13, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 17,
       17, 17, 18], dtype=int64)

In [101]:
test[::-1]  # reverse sequence in base python and numpy with the -1 step size

array([18, 17, 17, 17, 16, 16, 16, 16, 15, 15, 15, 15, 15, 14, 14, 14, 13,
       11, 10, 10], dtype=int64)

In [113]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [123]:
prices.sort()

In [135]:
expensive = np.sort(prices)[-3:]

In [136]:
expensive.mean()

57.49

In [137]:
expensive.min()

22.49

In [138]:
expensive.max()

99.99

In [141]:
len(np.unique(price_tiers))

3

Vectorization is the process of pushing array operations into optimized c code, which is easier and more efficient than writing for loops
broadcasting lets you perform vectorized operations with arrays of different size, where numpy will expand the smaller array to "fit" the larger one

In [143]:
retail_df = pd.read_csv("../data/retail_2016_2017.csv")

In [144]:
retail_df.head()

id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [145]:
sales_array = np.array(retail_df["sales"])
family_array = np.array(retail_df["family"])

In [174]:
prod_sarray = sales_array[family_array == "PRODUCE"]
sample = rng.integers(low=0, high=len(prod_sarray), size=len(prod_sarray))
sample = rng.random(len(prod_sarray))

In [172]:
len(family_array[family_array == "PRODUCE"])

31968

In [173]:
len(sales_array)

1054944

In [171]:
prod_sarray.size

31968

In [175]:
sample_sarray = prod_sarray[sample > 0.5]

In [176]:
s_mean = sample_sarray.mean()

In [177]:
s_median = np.median(sample_sarray)

In [178]:
category = np.where(
    (sample_sarray > s_mean) & (sample_sarray > s_median),
    "above_both",
    np.where(sample_sarray > s_median, "above_median", "below_both"),
)

In [168]:
category

array(['below_both', 'below_both', 'below_both', ..., 'below_both',
       'above_median', 'above_both'], dtype='<U12')

In [182]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sales_series = pd.Series(sales, name = "sales")

these are all numpy arrays, so panda is just stitching together numpy arrays to create stuff
values - data array in the series
index - jthe indes array in the series
name - the option nal for the series
dtype - data type of the elements in the values array

In [183]:
array = np.arange(5)
pd.Series(array)

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [185]:
series = pd.Series(np.arange(6), name="Test Array")

In [190]:
series.mean()

2.5

can change to index with 
Series.index = []
can change the name with
Series.name = "fancy name"

pandas data types

you can conver the data type in a pandas series by using the .astype() method and specifying the desired data type (if compatible)

In [198]:
array.astype("bool").sum()

4

In [85]:
oil = pd.read_csv("../data/oil.csv")

In [221]:
oil.head()

date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [86]:
oil = pd.read_csv("../data/oil.csv")
oil_array = pd.Series(oil["dcoilwtico"], name="oil_prices")
dates = pd.Series(oil["date"])

In [206]:
oil_series.dtype

dtype('float64')

In [207]:
oil_series.size

1218

In [208]:
oil_series.index

RangeIndex(start=0, stop=1218, step=1)

In [210]:
oil_series.mean()

67.71436595744682

In [214]:
(oil_series.dropna().astype("int").mean())

67.21361702127659

the index lets you easily access "rows" in pandas series or dataframe

one of the best uses of changing the index is in time series data. a timeseries index is very powerful when working with this kind of data

the .iloc[] method is the preferred way to access values by their positional index
- thid method works even when series have a custom, non-integer index

df.iloc[row position, column position]
- 0 first row, [5, 9] rows 5 and 9, [0:11] range of rows


the .loc[] method is the preferred way to access values by their custom labels

df.loc[row label, column label]
 - "pizza" single row ["mike", "ike"] multiple rows, ["mike", "ike"] slice

remember you can reset the index of the series/df with
df.reset_index(drop = True)

default df.reset_index(drop = False) will create column to store the old index

it is possible to have duplicate index vcalues in a pandas series or dataframe

access these indice by their label using .loc[] return all corresponding rows

In [215]:
series = pd.Series(np.arange(10))

In [216]:
series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [218]:
series.iloc[0:5]

0    0
1    1
2    2
3    3
4    4
dtype: int32

iloc operates like the normal indexing with the final number being non-inclusive
loc actualy is inclusive to the final index

In [18]:
oil_array.index = dates
oil_array.dropna(inplace=True)

In [19]:
oil_array.head()

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
Name: oil_prices, dtype: float64

In [9]:
len(oil_array)

1218

In [24]:
oil_array.iloc[:10].mean()

93.366

In [25]:
oil_array.iloc[-10:].mean()

47.30499999999999

In [27]:
oil_array.loc["2017-01-01":"2017-01-07"].reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: oil_prices, dtype: float64

you can filter series by passing a logical test into the .loc[] accessor
sales_series.loc[sales_series > 0]

In [28]:
mask = (oil_array > 0) & (oil_array < 100)

description | python operation | pandas method

equal == .eq()
not equal != .ne()
less than or equal <= .le()
less than < .lt()
greater than or equal >= .ge()
greater than > .gt()
membership test in .isin()
inverse membership test not in ~.isin()

in and not in don't work all that well in pandas, so you should get used to using the pandas method

you can sort series by their values or their index
.sort_values() method sorts a Series by its values in ascending order
.sort_values(ascending = False)
.sort_index(ascending = True)

In [29]:
oil_array.head()

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
Name: oil_prices, dtype: float64

In [34]:
oil_array.sort_values().iloc[:10].sort_index(ascending=False)

date
2016-02-16    29.05
2016-02-12    29.32
2016-02-11    26.19
2016-02-10    27.54
2016-02-09    27.96
2016-01-26    29.54
2016-01-21    29.55
2016-01-20    26.68
2016-01-19    28.47
2016-01-15    29.45
Name: oil_prices, dtype: float64

In [35]:
dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-16",
]

In [39]:
mask = (oil_array.index.isin(dates)) & (oil_array <= 50)

oil_array.loc[mask]

date
2017-05-03    47.79
Name: oil_prices, dtype: float64

string methods

.str then the following things

.strip(), .lstrip(), .rstrip() removes all leading and or?trailing characters (including spaces)
.upper(), .lower()
.slice(start:stop:step)
.count("string") counts all instances of "string"
.contains("string") teturns true is a given string is found, false if not
.replace("a", "b") replaces instances of string "a" with string "b"
.split("delimiter", expand = True) splits strings based on a given delimiter string, and returns a dataframe with a series for each split
.len() returns the length of each string in a a series
.startswith("string") .endswith("string")

In [40]:
oil_array.head()

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
Name: oil_prices, dtype: float64

In [41]:
expensive_oil = oil_array + (oil_array * 0.10) + 2

In [42]:
expensive_oil

date
2013-01-02    104.454
2013-01-03    104.267
2013-01-04    104.432
2013-01-07    104.520
2013-01-08    104.531
               ...   
2017-08-25     54.415
2017-08-28     53.040
2017-08-29     53.106
2017-08-30     52.556
2017-08-31     53.986
Name: oil_prices, Length: 1175, dtype: float64

In [43]:
diff = (
    abs(expensive_oil - expensive_oil.max())
    / ((expensive_oil + expensive_oil.max()) / 2)
) * 100

In [44]:
diff

date
2013-01-02    16.856612
2013-01-03    17.034512
2013-01-04    16.877526
2013-01-07    16.793893
2013-01-08    16.783444
                ...    
2017-08-25    77.785701
2017-08-28    79.947035
2017-08-29    79.842523
2017-08-30    80.715850
2017-08-31    78.456447
Name: oil_prices, Length: 1175, dtype: float64

In [59]:
month = oil_array.index.str[5:7].astype("int")

In [60]:
month

Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       ...
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
      dtype='int32', name='date', length=1175)

.count()
.first() .last()
.mean() .median()
.min() .max()
.argmax() .argmin() return the index for the smallest or largest values
.std(), .var()
.mad() mean absolute deviation
.prod() product of all the items
.sum() sum of all the items
.quantile([.25, .5, .75]) returns a specified percentile or list of percentiles - this method takes in the percentage in decimal not in 100% form

.unique()
.nunique()
.value_counts()
.value_counts(normalize = True) return the percentage of total for each category

In [61]:
oil_array.head()

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
Name: oil_prices, dtype: float64

In [69]:
oil_array.iloc[month == 4].sum()

7137.44

In [70]:
oil_array.iloc[month == 4].mean()

68.62923076923076

In [81]:
mask = (month == 1) | (month == 2)

oil_array.iloc[mask].count()

197

In [78]:
oil_array[oil_array.index.str[5:7].isin(["01", "02"])].count()

197

In [72]:
oil_array.quantile([0.10, 0.90])

0.1     41.716
0.9    103.070
Name: oil_prices, dtype: float64

In [83]:
oil_array.astype("int").value_counts(normalize=True)

oil_prices
48    0.046809
47    0.045957
93    0.045106
46    0.045106
45    0.044255
        ...   
73    0.000851
76    0.000851
83    0.000851
28    0.000851
86    0.000851
Name: proportion, Length: 77, dtype: float64

missing data in pandas is often represented by numpy "NaN" values
which stand for not a number
pandas treats NaN values as a float, which allows them to be used invectorized operations

in the pandas methods you can specifiy the argument fill_value = int, and it will replace an NaN with the fill value


pandas released its own missing data type NA in december 2020

this allows missing values to be stored as integers


.isna() and .value_counts() methods let you identify missing data in series

checklist.isna().sum() returns the count of NaN of NA values

by default .value_counts(dropna = True) but if we set dropna = False it will also return the valuecounts of NaN 

.dropna() and .fillna() methods let you handle missing data in series.

In [87]:
oil_array.isna().sum()

43

In [90]:
oil_array.fillna(oil_array.median(), inplace=True)

In [91]:
oil_array.isna().sum()

0

In [92]:
oil_array.where(~oil_array.isin([51.44, 47.83]), np.NaN)

0       53.19
1       93.14
2       92.97
3       93.12
4       93.20
        ...  
1213    47.65
1214    46.40
1215    46.46
1216    45.96
1217    47.26
Name: oil_prices, Length: 1218, dtype: float64

In [93]:
oil_array.isna().sum()

0

In [94]:
oil = pd.read_csv("../data/oil.csv")
oil_array = pd.Series(oil["dcoilwtico"], name="oil_prices")
dates = pd.Series(oil["date"])

In [95]:
oil_array.isna().sum()

43

.apply() method lets you apply custom functions to pandas series
- this function will not be vectorized, so it's not as efficient as native functions

pandas .where() method, returns series values based on a logical condition

df.where(
    logical test,
    value if False,
    inplace = False
)

can only specify values if false, keeps original values for True 

In [96]:
oil_array.quantile(0.9)

103.07

In [97]:
mask = (oil_array > oil_array.quantile(0.9)) | oil_array.isna()

can_by = np.where(mask, "wait", "buy")

In [98]:
can_by

array(['wait', 'buy', 'buy', ..., 'buy', 'buy', 'buy'], dtype='<U4')

In [99]:
mask = (oil_array.index == "2016-12-23") | (oil_array.index == "2017-15-10")

final_price = np.where(mask, oil_array * 0.9, oil_array * 1.1)

In [100]:
final_price

array([    nan, 102.454, 102.267, ...,  51.106,  50.556,  51.986])